// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CurrentContextReadViewModel
    {
        /// <summary>
        /// Initializes a new instance of the CurrentContextReadViewModel
        /// class.
        /// </summary>
        public CurrentContextReadViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CurrentContextReadViewModel
        /// class.
        /// </summary>
        public CurrentContextReadViewModel(string userId = default(string), string email = default(string), string displayName = default(string))
        {
            UserId = userId;
            Email = email;
            DisplayName = displayName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

    }
}
