// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ElevationReadViewModel
    {
        /// <summary>
        /// Initializes a new instance of the ElevationReadViewModel class.
        /// </summary>
        public ElevationReadViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ElevationReadViewModel class.
        /// </summary>
        public ElevationReadViewModel(SpriteLayerReadViewModel baseLayer = default(SpriteLayerReadViewModel), SpriteLayerReadViewModel terrainLayer = default(SpriteLayerReadViewModel), SpriteLayerReadViewModel structureLayer = default(SpriteLayerReadViewModel), SpriteLayerReadViewModel partitionLayer = default(SpriteLayerReadViewModel), SpriteLayerReadViewModel ceilingObjectLayer = default(SpriteLayerReadViewModel), SpriteLayerReadViewModel floorObjectLayer = default(SpriteLayerReadViewModel), SpriteLayerReadViewModel suspendedObjectLayer = default(SpriteLayerReadViewModel), SpriteLayerReadViewModel wallObjectLayer = default(SpriteLayerReadViewModel), GatewayLayerReadViewModel gatewayLayer = default(GatewayLayerReadViewModel))
        {
            BaseLayer = baseLayer;
            TerrainLayer = terrainLayer;
            StructureLayer = structureLayer;
            PartitionLayer = partitionLayer;
            CeilingObjectLayer = ceilingObjectLayer;
            FloorObjectLayer = floorObjectLayer;
            SuspendedObjectLayer = suspendedObjectLayer;
            WallObjectLayer = wallObjectLayer;
            GatewayLayer = gatewayLayer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baseLayer")]
        public SpriteLayerReadViewModel BaseLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "terrainLayer")]
        public SpriteLayerReadViewModel TerrainLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "structureLayer")]
        public SpriteLayerReadViewModel StructureLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "partitionLayer")]
        public SpriteLayerReadViewModel PartitionLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ceilingObjectLayer")]
        public SpriteLayerReadViewModel CeilingObjectLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "floorObjectLayer")]
        public SpriteLayerReadViewModel FloorObjectLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suspendedObjectLayer")]
        public SpriteLayerReadViewModel SuspendedObjectLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "wallObjectLayer")]
        public SpriteLayerReadViewModel WallObjectLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gatewayLayer")]
        public GatewayLayerReadViewModel GatewayLayer { get; set; }

    }
}
