// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ElevationViewModel
    {
        /// <summary>
        /// Initializes a new instance of the ElevationViewModel class.
        /// </summary>
        public ElevationViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ElevationViewModel class.
        /// </summary>
        public ElevationViewModel(SpriteLayerViewModel baseLayer = default(SpriteLayerViewModel), TerrainSpriteLayerViewModel terrainLayer = default(TerrainSpriteLayerViewModel), ObjectSpriteLayerViewModel structureLayer = default(ObjectSpriteLayerViewModel), SpriteLayerViewModel partitionLayer = default(SpriteLayerViewModel), ObjectSpriteLayerViewModel ceilingObjectLayer = default(ObjectSpriteLayerViewModel), ObjectSpriteLayerViewModel floorObjectLayer = default(ObjectSpriteLayerViewModel), ObjectSpriteLayerViewModel suspendedObjectLayer = default(ObjectSpriteLayerViewModel), ObjectSpriteLayerViewModel wallObjectLayer = default(ObjectSpriteLayerViewModel), GatewayLayerViewModel gatewayLayer = default(GatewayLayerViewModel))
        {
            BaseLayer = baseLayer;
            TerrainLayer = terrainLayer;
            StructureLayer = structureLayer;
            PartitionLayer = partitionLayer;
            CeilingObjectLayer = ceilingObjectLayer;
            FloorObjectLayer = floorObjectLayer;
            SuspendedObjectLayer = suspendedObjectLayer;
            WallObjectLayer = wallObjectLayer;
            GatewayLayer = gatewayLayer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baseLayer")]
        public SpriteLayerViewModel BaseLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "terrainLayer")]
        public TerrainSpriteLayerViewModel TerrainLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "structureLayer")]
        public ObjectSpriteLayerViewModel StructureLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "partitionLayer")]
        public SpriteLayerViewModel PartitionLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ceilingObjectLayer")]
        public ObjectSpriteLayerViewModel CeilingObjectLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "floorObjectLayer")]
        public ObjectSpriteLayerViewModel FloorObjectLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suspendedObjectLayer")]
        public ObjectSpriteLayerViewModel SuspendedObjectLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "wallObjectLayer")]
        public ObjectSpriteLayerViewModel WallObjectLayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gatewayLayer")]
        public GatewayLayerViewModel GatewayLayer { get; set; }

    }
}
