// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GameCreateViewModel
    {
        /// <summary>
        /// Initializes a new instance of the GameCreateViewModel class.
        /// </summary>
        public GameCreateViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GameCreateViewModel class.
        /// </summary>
        public GameCreateViewModel(string name = default(string))
        {
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
