// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GatewayLayerReadViewModel
    {
        /// <summary>
        /// Initializes a new instance of the GatewayLayerReadViewModel class.
        /// </summary>
        public GatewayLayerReadViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GatewayLayerReadViewModel class.
        /// </summary>
        public GatewayLayerReadViewModel(IDictionary<string, GatewayReadViewModel> grid = default(IDictionary<string, GatewayReadViewModel>))
        {
            Grid = grid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grid")]
        public IDictionary<string, GatewayReadViewModel> Grid { get; set; }

    }
}
