// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GatewayViewModel
    {
        /// <summary>
        /// Initializes a new instance of the GatewayViewModel class.
        /// </summary>
        public GatewayViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GatewayViewModel class.
        /// </summary>
        public GatewayViewModel(string mapId = default(string), CoordinateViewModel mapCoordinate = default(CoordinateViewModel))
        {
            MapId = mapId;
            MapCoordinate = mapCoordinate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mapId")]
        public string MapId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mapCoordinate")]
        public CoordinateViewModel MapCoordinate { get; set; }

    }
}
