// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GatewayLayerViewModel
    {
        /// <summary>
        /// Initializes a new instance of the GatewayLayerViewModel class.
        /// </summary>
        public GatewayLayerViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GatewayLayerViewModel class.
        /// </summary>
        /// <param name="grid">Layer key represents a coordinate and should be
        /// formatted as "{int x}:{int y}".</param>
        public GatewayLayerViewModel(IDictionary<string, GatewayViewModel> grid = default(IDictionary<string, GatewayViewModel>))
        {
            Grid = grid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets layer key represents a coordinate and should be
        /// formatted as "{int x}:{int y}".
        /// </summary>
        [JsonProperty(PropertyName = "grid")]
        public IDictionary<string, GatewayViewModel> Grid { get; set; }

    }
}
