// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for GetGames operation.
    /// </summary>
    public partial class GetGamesHeaders
    {
        /// <summary>
        /// Initializes a new instance of the GetGamesHeaders class.
        /// </summary>
        public GetGamesHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetGamesHeaders class.
        /// </summary>
        /// <param name="xTotalCount">The total number of filtered
        /// resources.</param>
        public GetGamesHeaders(double? xTotalCount = default(double?))
        {
            XTotalCount = xTotalCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the total number of filtered resources.
        /// </summary>
        [JsonProperty(PropertyName = "X-Total-Count")]
        public double? XTotalCount { get; set; }

    }
}
