// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MapSizeViewModel
    {
        /// <summary>
        /// Initializes a new instance of the MapSizeViewModel class.
        /// </summary>
        public MapSizeViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MapSizeViewModel class.
        /// </summary>
        public MapSizeViewModel(int? width = default(int?), int? height = default(int?))
        {
            Width = width;
            Height = height;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public int? Width { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public int? Height { get; set; }

    }
}
