// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserReadViewModel
    {
        /// <summary>
        /// Initializes a new instance of the UserReadViewModel class.
        /// </summary>
        public UserReadViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserReadViewModel class.
        /// </summary>
        public UserReadViewModel(string id = default(string), string email = default(string), string displayName = default(string), System.DateTime? dateCreated = default(System.DateTime?), System.DateTime? dateModified = default(System.DateTime?), System.DateTime? dateActive = default(System.DateTime?))
        {
            Id = id;
            Email = email;
            DisplayName = displayName;
            DateCreated = dateCreated;
            DateModified = dateModified;
            DateActive = dateActive;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateModified")]
        public System.DateTime? DateModified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateActive")]
        public System.DateTime? DateActive { get; set; }

    }
}
