// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserCreateViewModel
    {
        /// <summary>
        /// Initializes a new instance of the UserCreateViewModel class.
        /// </summary>
        public UserCreateViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserCreateViewModel class.
        /// </summary>
        public UserCreateViewModel(string email = default(string), string displayName = default(string), string password = default(string))
        {
            Email = email;
            DisplayName = displayName;
            Password = password;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

    }
}
