// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WorldMapSummaryViewModel
    {
        /// <summary>
        /// Initializes a new instance of the WorldMapSummaryViewModel class.
        /// </summary>
        public WorldMapSummaryViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WorldMapSummaryViewModel class.
        /// </summary>
        public WorldMapSummaryViewModel(string id = default(string), string gameId = default(string), string name = default(string), string createdBy = default(string))
        {
            Id = id;
            GameId = gameId;
            Name = name;
            CreatedBy = createdBy;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gameId")]
        public string GameId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; set; }

    }
}
