// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WWA.RestApi.CsharpClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class WorldMapReadViewModel
    {
        /// <summary>
        /// Initializes a new instance of the WorldMapReadViewModel class.
        /// </summary>
        public WorldMapReadViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WorldMapReadViewModel class.
        /// </summary>
        /// <param name="elevations">Elevations key is an int that represents
        /// the y index of the corresponding Elevation object.</param>
        public WorldMapReadViewModel(string id = default(string), string gameId = default(string), string name = default(string), string createdBy = default(string), System.DateTime? dateCreated = default(System.DateTime?), System.DateTime? dateModified = default(System.DateTime?), MapSizeViewModel size = default(MapSizeViewModel), IDictionary<string, ElevationReadViewModel> elevations = default(IDictionary<string, ElevationReadViewModel>))
        {
            Id = id;
            GameId = gameId;
            Name = name;
            CreatedBy = createdBy;
            DateCreated = dateCreated;
            DateModified = dateModified;
            Size = size;
            Elevations = elevations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gameId")]
        public string GameId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateModified")]
        public System.DateTime? DateModified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public MapSizeViewModel Size { get; set; }

        /// <summary>
        /// Gets or sets elevations key is an int that represents the y index
        /// of the corresponding Elevation object.
        /// </summary>
        [JsonProperty(PropertyName = "elevations")]
        public IDictionary<string, ElevationReadViewModel> Elevations { get; set; }

    }
}
