/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing AccessTokenCreateViewModel.
 */
export interface AccessTokenCreateViewModel {
  email: string;
  password: string;
}

/**
 * An interface representing UserSummaryViewModel.
 */
export interface UserSummaryViewModel {
  id?: string;
  email?: string;
  displayName?: string;
}

/**
 * An interface representing UserCreateViewModel.
 */
export interface UserCreateViewModel {
  email?: string;
  displayName?: string;
  password?: string;
}

/**
 * An interface representing UserReadViewModel.
 */
export interface UserReadViewModel {
  id?: string;
  email?: string;
  displayName?: string;
  dateCreated?: Date;
  dateModified?: Date;
  dateActive?: Date;
}

/**
 * An interface representing UserReplaceViewModel.
 */
export interface UserReplaceViewModel {
  email?: string;
  displayName?: string;
}

/**
 * An interface representing WwaRestApiClientOptions.
 */
export interface WwaRestApiClientOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface WwaRestApiClientCreateAccessTokenOptionalParams extends msRest.RequestOptionsBase {
  body?: AccessTokenCreateViewModel;
}

/**
 * Optional Parameters.
 */
export interface WwaRestApiClientQueryUsersOptionalParams extends msRest.RequestOptionsBase {
  email?: string;
}

/**
 * Optional Parameters.
 */
export interface WwaRestApiClientGetUsersOptionalParams extends msRest.RequestOptionsBase {
  skip?: number;
  take?: number;
  sortField?: string;
  /**
   * Possible values include: 'Ascending', 'Descending'
   */
  sortDirection?: SortDirection;
  search?: string;
}

/**
 * Optional Parameters.
 */
export interface WwaRestApiClientCreateUserOptionalParams extends msRest.RequestOptionsBase {
  body?: UserCreateViewModel;
}

/**
 * Optional Parameters.
 */
export interface WwaRestApiClientReplaceUserOptionalParams extends msRest.RequestOptionsBase {
  body?: UserReplaceViewModel;
}

/**
 * Defines headers for GetUsers operation.
 */
export interface GetUsersHeaders {
  /**
   * The total number of filtered resources.
   */
  xTotalCount: number;
}

/**
 * Defines values for SortDirection.
 * Possible values include: 'Ascending', 'Descending'
 * @readonly
 * @enum {string}
 */
export type SortDirection = 'Ascending' | 'Descending';

/**
 * Contains response data for the createAccessToken operation.
 */
export type CreateAccessTokenResponse = {
  /**
   * The parsed response body.
   */
  body: string;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: string;
    };
};

/**
 * Contains response data for the getUsers operation.
 */
export type GetUsersResponse = Array<UserSummaryViewModel> & GetUsersHeaders & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: GetUsersHeaders;

      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: UserSummaryViewModel[];
    };
};

/**
 * Contains response data for the createUser operation.
 */
export type CreateUserResponse = UserReadViewModel & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: UserReadViewModel;
    };
};

/**
 * Contains response data for the getUser operation.
 */
export type GetUserResponse = UserReadViewModel & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: UserReadViewModel;
    };
};

/**
 * Contains response data for the replaceUser operation.
 */
export type ReplaceUserResponse = UserReadViewModel & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: UserReadViewModel;
    };
};
