/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const AccessTokenCreateViewModel: msRest.CompositeMapper = {
  serializedName: "AccessTokenCreateViewModel",
  type: {
    name: "Composite",
    className: "AccessTokenCreateViewModel",
    modelProperties: {
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      password: {
        required: true,
        serializedName: "password",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const UserSummaryViewModel: msRest.CompositeMapper = {
  serializedName: "UserSummaryViewModel",
  type: {
    name: "Composite",
    className: "UserSummaryViewModel",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      displayName: {
        serializedName: "displayName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const UserCreateViewModel: msRest.CompositeMapper = {
  serializedName: "UserCreateViewModel",
  type: {
    name: "Composite",
    className: "UserCreateViewModel",
    modelProperties: {
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      displayName: {
        serializedName: "displayName",
        type: {
          name: "String"
        }
      },
      password: {
        serializedName: "password",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const UserReadViewModel: msRest.CompositeMapper = {
  serializedName: "UserReadViewModel",
  type: {
    name: "Composite",
    className: "UserReadViewModel",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      displayName: {
        serializedName: "displayName",
        type: {
          name: "String"
        }
      },
      dateCreated: {
        serializedName: "dateCreated",
        type: {
          name: "DateTime"
        }
      },
      dateModified: {
        serializedName: "dateModified",
        type: {
          name: "DateTime"
        }
      },
      dateActive: {
        serializedName: "dateActive",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const UserReplaceViewModel: msRest.CompositeMapper = {
  serializedName: "UserReplaceViewModel",
  type: {
    name: "Composite",
    className: "UserReplaceViewModel",
    modelProperties: {
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      displayName: {
        serializedName: "displayName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetUsersHeaders: msRest.CompositeMapper = {
  serializedName: "getusers-headers",
  type: {
    name: "Composite",
    className: "GetUsersHeaders",
    modelProperties: {
      xTotalCount: {
        serializedName: "x-total-count",
        type: {
          name: "Number"
        }
      }
    }
  }
};
