/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const email: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "email"
  ],
  mapper: {
    serializedName: "email",
    type: {
      name: "String"
    }
  }
};
export const id: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    serializedName: "id",
    type: {
      name: "String"
    }
  }
};
export const search: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "search"
  ],
  mapper: {
    serializedName: "Search",
    type: {
      name: "String"
    }
  }
};
export const skip: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "skip"
  ],
  mapper: {
    serializedName: "Skip",
    type: {
      name: "Number"
    }
  }
};
export const sortDirection: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "sortDirection"
  ],
  mapper: {
    serializedName: "SortDirection",
    type: {
      name: "String"
    }
  }
};
export const sortField: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "sortField"
  ],
  mapper: {
    serializedName: "SortField",
    type: {
      name: "String"
    }
  }
};
export const take: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "take"
  ],
  mapper: {
    serializedName: "Take",
    type: {
      name: "Number"
    }
  }
};
